### 매장정보 가져오기
GET http://localhost:8080/store/store-list?lat=37.518648&lng=127.0032654
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG5hdmVyLmNvbSIsImlhdCI6MTcxMzQxMTYyOCwiZXhwIjoxNzEzNDEzMDY4fQ.Z16eAlEKOQ8PXmKxtpUuic0bjGYh8aDfyaipkQPEnFM"